name: Retrospective Reminder

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 23 * * 4
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Send Retrospective Reminder
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" --data-urlencode 'content=📝 ${{ secrets.ROLE_TAG }} mmm it's time. let's go! how could you forget? {it's retro time!} https://c.tenor.com/jhHMmyw7g5oAAAAM/retrospective.gif'
